### ISSUE TITLE
Do not write to the filesystem if not needed

### ISSUE THREAD

**Issue by 1ed** [aaronransley/nuxt-winston-log#4]
Hello! When I use the logger with the console transport I don't want to write the filesystem in any way. This can be an issue for read only filesystems. This line https://github.com/aaronransley/nuxt-winston-log/blob/4219b7711f8b446cac9a99eec909f3190a95346d/index.js#L21 creates the logs diretory anyway and there is no way to override this behaviour.

**Comment by tyriis** [comment]
First of all thanks for your work!

Just hit the same problem during a CI build. This should be configurable or removed if possible.

**Comment by Jean-Jacques-Nuoan** [comment]
please tell me if this issue closed

**Comment by tyriis** [comment]
@Jean-Jacques-Nuoan 
No, it is not closed, it is still present, initializing the logger, writes to a file system no matter what transport is defined.

**Comment by aaronransley** [comment]
Hey @tyriis, @1ed, and @Jean-Jacques-Nuoan

~~I'm not able to find time to iterate on this right now, but it should be straight forward to add an additional option to the plugin, wrap filesystem assumptions in a boolean check, etc. I'll happily merge PRs, but can't add this myself at the moment.~~

Working on adding these features now.

**Comment by aaronransley** [comment]
@1ed @tyriis @Jean-Jacques-Nuoan This should be resolved with 1.2.0 release. Let me know if you run into any snags!

**Comment by Jean-Jacques-Nuoan** [comment]
thanks!
