### ISSUE TITLE
How to use $winstonLog on asyncData method ?

### ISSUE THREAD

**Issue by sdailly** [aaronransley/nuxt-winston-log#5]
Hello,

I would like use `$winstonLog` on `asyncData` method.
But `Property '$winstonLog' does not exist on type 'Context'` ... 

Do you have an idea for use it ? 

```
async asyncData(ctx: Context) {
  ctx.$winstonLog.info('Hello');
}
```

Thank you

**Comment by tyriis** [comment]
at least from the README it looks like ctx is the 2nd arg not the first.

```javascript
async nuxtServerInit({ store, commit }, { req, $winstonLog }) {
    // ...
    $winstonLog.info(`x-forwarded-host: ${req.headers['x-forwarded-host']}`)
    // ...
  }
```

**Comment by aaronransley** [comment]
@sdailly I haven't attempted to use `$winstonLog` within `asyncData` yet, so bear with me. I believe that `asyncData` is an isomorphic function, so it'll be called by Nuxt's server and client runtimes both. However, the `$winstonLog` injection happens via a server-side plugin (see `~/plugin.server.js`) and so it wouldn't be available in client side `asyncData` calls.

It might be best to wrap your calls to `$winstonLog` with a `process.server` check to ensure only the server-side `asyncData` execution attempts to access `$winstonLog`, e.g.

```
async asyncData(ctx: Context) {
  if (process.server) {
    ctx.$winstonLog.info('Hello');
  }
}
```

**Comment by sdailly** [comment]
My problem is related to typescript and the fact that there is no type in module #8
