### ISSUE TITLE
How to log only errors, but not info messages?

### ISSUE THREAD

**Issue by vaban-ru** [aaronransley/nuxt-winston-log#6]
Hello, can i log only error events? Give me example please.

**Comment by aaronransley** [comment]
Hi @webzlodimir, I would recommend [looking into the Winston documentation](https://github.com/winstonjs/winston#usage). As-is, there isn't an option to disable the info logging on the Nuxt middleware events, but you can set your logger `level` to `error` to discard any lower level messages such as `info`.
